### ISSUE TITLE
Update OT to GA Version 1.0.0 or greater

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [NovatecConsulting/boomerang-opentelemetry-plugin#26]
Opentelemetry-js has reached GA with Version 1.0.0
[v 1.0.0](https://github.com/open-telemetry/opentelemetry-js/releases/tag/stable%2Fv1.0.0)
This Plugin should updated to this Version.

**Comment by SaschaBrechmannVHV** [comment]
Now we are at [OT-JS SDK Version 1.7](https://github.com/open-telemetry/opentelemetry-js/releases/tag/v1.7.0)

**Comment by EddeCCC** [comment]
Hi @SaschaBrechmannVHV,
we are now using the latest OT.js SDK version 1.21.0

Closing the Issue.
