### ISSUE TITLE
include "OpenTelemetry Browser Detector" package

### ISSUE THREAD

**Issue by SaschaBrechmannVHV** [NovatecConsulting/boomerang-opentelemetry-plugin#36]
The browser identification attributes will be added to the resource spans when traces are created. These attributes include platform, brands, mobile, language if the browser supports the userAgentData api, otherwise it will contain only the user_agent informations

[OpenTelemetry Browser Detector](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-browser-detector)

**Comment by mc-chaos** [comment]
@EddeCCC : dies this release include the browser-detection?
Regards Sascha

**Comment by EddeCCC** [comment]
Hi @mc-chaos,
the current release does not yet include the browser-detection. This feature will be added in the next version 0.48.0-2

Regards Edi

**Comment by EddeCCC** [comment]
Hello @SaschaBrechmannVHV,

the plugin was added in the last [release](https://github.com/NovatecConsulting/boomerang-opentelemetry-plugin/releases/tag/0.48.0-2).

Regards Edi
